---
title: "shiny_app_test"
author: "Shreena Pyakurel"
date: "11/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(geospaar)
library(Phenmap)
#install.packages("greenbrown", repos="http://R-Forge.R-project.org")
library(greenbrown)
worc_EVI <- read.csv("../inst/extdata/worc_evi.csv")
worc_EVI %>% as.data.frame()


#create raster
e <- extent(worc_EVI[,(1:2)])
r <- raster(e, ncol=16, nrow=18, crs= "+proj=longlat +datum=WGS84")
evi_years<- rasterize(worc_EVI[,1:2], r, worc_EVI[,3:length(worc_EVI)], fun=mean)
plot(evi_years)

#phenology
all_pixels <- worc_EVI %>%
  select (-c(x, y)) %>%
  arrange() %>%
  slice(1:nrow(worc_EVI)) %>%
  t()
#time series
EVIseries <- ts(all_pixels, start=c(2000, 1), end=c(2007, 12), frequency=12)

#interpolate
#Create empty lists for lapply
Yt_interpolate_daily <- list()
Yt_interpolate_daily2 <- list()
Phen_2000_2007 <- list()



###############################################
library(doParallel)  #Foreach Parallel Adaptor parallel processing to extrsct metrics 
library(foreach)
library(parallel)

model.mse <- function(x){
  Yt_interpolate_daily[[x]]  <- greenbrown::TsPP(EVIseries[,x], fpg = FillPermanentGaps, tsgf=TSGFspline)
}

UseCores <- detectCores() - 1
ww <- ncol(EVIseries)
system.time({
  clust <- makeCluster(UseCores)
  clusterEvalQ(clust, library("greenbrown"))
  clusterExport(clust, c("EVIseries","Yt_interpolate_daily"))
  Yt_interpolate_daily2 <- parLapply(clust, seq(ww), model.mse)})


model_phen <- function(x){
  Phen_2000_2007[[x]] <- Phenology(Yt_interpolate_daily2[[x]], approach="White")
}

system.time({
  # clust <- makeCluster(UseCores)
  clusterEvalQ(clust, library("greenbrown"))
  clusterExport(clust, c('Phen_2000_2007', 'Yt_interpolate_daily2'))
  Phen_2000_2007 <- parLapply(clust, seq(ww), model_phen)})



##########################################################
#interpolation graph 
plot(Yt_interpolate_daily2[[1]] )

#years to be added to data frame  
years <- c(2000:2007)
years <- as.numeric(years)

#Phenology regression plot 
plot(Phen_2000_2007[[1]])


#extract metrics of choice 
sos <- list()
eos <- list()
los <- list()
pop <- list()
for(i in seq(ncol(EVIseries))){
  sos[[i]] <-  as.numeric( Phen_2000_2007[[i]][["sos"]])
  eos[[i]] <-  as.numeric( Phen_2000_2007[[i]][["eos"]])
  los[[i]] <-  as.numeric( Phen_2000_2007[[i]][["los"]])
  pop[[i]] <-  as.numeric( Phen_2000_2007[[i]][["pop"]])
}
sos <- unlist(sos)
eos <- unlist(eos)
los <- unlist(los)
pop <- unlist(pop)

#create dataframe of metrics 
coords <-worc_EVI %>% select(x, y)
coords2 <- coords %>% slice(rep(1:n(), each = 8))
DF_phenmet_test <- data.frame(coords2,sos, eos, los, pop) %>% cbind(years)
DF_phenmet_testarranged <- DF_phenmet_test %>% arrange(years)
DF_phenmet_testarranged_sf = st_as_sf(DF_phenmet_testarranged, coords = c("x", "y"), crs = 4326)

#raster brick of metrics 
e <- extent(worc_EVI[,(1:2)])
r <- raster(e, ncol = 16, nrow = 18, crs= '+proj=longlat +datum=WGS84')
raster_brick <- do.call(stack, lapply(unique(DF_phenmet_testarranged$years), function(yr){
  years_sub <- DF_phenmet_testarranged %>% filter(years == yr)
  rst <- rasterize(years_sub[, 1:2], r, years_sub[, c(3:(ncol(years_sub) - 1))], fun = mean)
  names(rst) <- paste(names(rst), yr, sep = '_')
  rst
}))
# if statement choose plot for correct EVI and NDVI
plot(raster_brick)
    

rleaf<- raster_brick$sos_2000

library(leaflet)
leaflet() %>% addTiles() %>%
  addRasterImage(r, opacity = 0.8)


```


```{r}
library(shiny)
library(shinydashboard)
library(geospaar)
years <- c(2000:2007)
header <- dashboardHeader(
  title = 'Phenology Metrics')
sidebar <- dashboardSidebar(
  menuItem("Years", tabName = "select Year",
           selectInput("start_date", "Start Date:", years),
           selectInput("end_date", "End Date:", years)))
body <- dashboardBody(
  fluidRow(
     box(div(style='width:750px;overflow-x: scroll; height:500px;overflow-y: scroll;',
            leafletOutput("mymap"), height = 500, width = 500)),
     box(div(style='width:750px;overflow-x: scroll; height:500px;overflow-y: scroll;',
            plotOutput("pt", height = 500, width = 500))), 
     box(div(style='width:750px;overflow-x: scroll; height:500px;overflow-y: scroll;',
            plotOutput("interpolated", height = 500, width = 500))), 
    box(div(style='width:750px;overflow-x: scroll; height:500px;overflow-y: scroll;',
            plotOutput("regression", height = 500, width = 500)))))
  
   
 

ui <- dashboardPage(
  header,
  sidebar,
  body)

server <- function(input, output) {
  output$pt <- renderPlot({
    years1 <- DF_phenmet_testarranged %>%
      filter(years >= input$start_date &
               years <= input$end_date)
    
    
    e <- extent(worc_EVI[,(1:2)])
    r <- raster(e, ncol = 16, nrow = 18, crs= '+proj=longlat +datum=WGS84')
    raster_brick <- do.call(stack, lapply(unique(years1$years), function(yr){
      years_sub <- years1 %>% filter(years == yr)
      rst <- rasterize(years_sub[, 1:2], r, years_sub[, c(3:(ncol(years_sub) - 1))], fun = mean)
      names(rst) <- paste(names(rst), yr, sep = '_')
      rst
    }))
    # if statement choose plot for correct EVI and NDVI
    plot(raster_brick)
  })

  output$regression <- renderPlot({
  plot(Phen_2000_2007[[1]])
  })
  
  output$interpolated <- renderPlot({
  plot(Yt_interpolate_daily2[[1]], ylab = "Daily Interpolated Value")
  })
  
  pal <- colorNumeric(c('#FFFFFF', '#CE7E45', '#DF923D', '#F1B555', '#FCD163', '#99B718', '#74A901',
    '#66A000', '#529400', '#3E8601', '#207401', '#056201', '#004C00', '#023B01',
    '#012E01', '#011D01', '#011301'), values(evi_years),
  na.color = "transparent")
  output$mymap <- renderLeaflet({
    leaflet() %>%
      addProviderTiles(providers$Stamen.TonerLite,
        options = providerTileOptions(noWrap = TRUE)
      ) %>% addRasterImage(evi_years$X1.1.2000, colors = pal) %>% 
      addLegend(pal = pal, values = values(evi_years$X1.1.2000),
    title = "EVI values for 01/01 2000")
  })
}

shinyApp(ui, server)
```

